INSERT INTO ingrediente VALUES ('Aceite de soja', 'Aceites y materias grasas');
INSERT INTO ingrediente VALUES ('Aceite de maíz', 'Aceites y materias grasas');
INSERT INTO ingrediente VALUES ('Aceite de oliva', 'Aceites y materias grasas');
INSERT INTO ingrediente VALUES ('Nata o crema de leche', 'Productos lácteos');
INSERT INTO ingrediente VALUES ('Yogur', 'Productos lácteos');
INSERT INTO ingrediente VALUES ('Leche', 'Productos lácteos');
INSERT INTO ingrediente VALUES ('Helado', 'Productos lácteos');
INSERT INTO ingrediente VALUES ('Queso', 'Productos lácteos');
INSERT INTO ingrediente VALUES ('Alubias', 'Legumbres');
INSERT INTO ingrediente VALUES ('Garbanzos', 'Legumbres');
INSERT INTO ingrediente VALUES ('Lentejas', 'Legumbres');
INSERT INTO ingrediente VALUES ('Soja', 'Legumbres');
INSERT INTO ingrediente VALUES ('Setas', 'Setas y verduras');
INSERT INTO ingrediente VALUES ('Hongos', 'Setas y verduras');
INSERT INTO ingrediente VALUES ('Coles', 'Setas y verduras');
INSERT INTO ingrediente VALUES ('Pimientas', 'Setas y verduras');
INSERT INTO ingrediente VALUES ('Patata', 'Setas y verduras');
INSERT INTO ingrediente VALUES ('Raíces y tubérculos', 'Setas y verduras');
INSERT INTO ingrediente VALUES ('Lechugas', 'Setas y verduras');
INSERT INTO ingrediente VALUES ('Acelga', 'Setas y verduras');
INSERT INTO ingrediente VALUES ('Alcachofa', 'Setas y verduras');
INSERT INTO ingrediente VALUES ('Batata', 'Setas y verduras');
INSERT INTO ingrediente VALUES ('Berenjena', 'Setas y verduras');
INSERT INTO ingrediente VALUES ('Berro', 'Setas y verduras');
INSERT INTO ingrediente VALUES ('Brócoli', 'Setas y verduras');
INSERT INTO ingrediente VALUES ('Brecol', 'Setas y verduras');
INSERT INTO ingrediente VALUES ('Calabacín', 'Setas y verduras');
INSERT INTO ingrediente VALUES ('Calabaza', 'Setas y verduras');
INSERT INTO ingrediente VALUES ('Cardo', 'Setas y verduras');
INSERT INTO ingrediente VALUES ('Cebolla', 'Setas y verduras');
INSERT INTO ingrediente VALUES ('Cebolleta', 'Setas y verduras');
INSERT INTO ingrediente VALUES ('Coles de Bruselas', 'Setas y verduras');
INSERT INTO ingrediente VALUES ('Coliflor', 'Setas y verduras');
INSERT INTO ingrediente VALUES ('Endivia', 'Setas y verduras');
INSERT INTO ingrediente VALUES ('Tomate', 'Setas y verduras');
INSERT INTO ingrediente VALUES ('Zanahoria', 'Setas y verduras');
INSERT INTO ingrediente VALUES ('Escarola', 'Setas y verduras');
INSERT INTO ingrediente VALUES ('Espárrago', 'Setas y verduras');
INSERT INTO ingrediente VALUES ('Espinaca', 'Setas y verduras');
INSERT INTO ingrediente VALUES ('Guisante', 'Setas y verduras');
INSERT INTO ingrediente VALUES ('Habas', 'Setas y verduras');
INSERT INTO ingrediente VALUES ('Hinojo', 'Setas y verduras');
INSERT INTO ingrediente VALUES ('Judías', 'Setas y verduras');
INSERT INTO ingrediente VALUES ('Maíz', 'Setas y verduras');
INSERT INTO ingrediente VALUES ('Palmito', 'Setas y verduras');
INSERT INTO ingrediente VALUES ('Pepino', 'Setas y verduras');
INSERT INTO ingrediente VALUES ('Pimiento', 'Setas y verduras');
INSERT INTO ingrediente VALUES ('Puerro', 'Setas y verduras');
INSERT INTO ingrediente VALUES ('Remolacha', 'Setas y verduras');
INSERT INTO ingrediente VALUES ('Albaricoque', 'Frutas');
INSERT INTO ingrediente VALUES ('Aguacate', 'Frutas');
INSERT INTO ingrediente VALUES ('Cereza', 'Frutas');
INSERT INTO ingrediente VALUES ('Mango', 'Frutas');
INSERT INTO ingrediente VALUES ('Melocotones', 'Frutas');
INSERT INTO ingrediente VALUES ('Nectarina', 'Frutas');
INSERT INTO ingrediente VALUES ('Ciruela', 'Frutas');
INSERT INTO ingrediente VALUES ('Fruta del bosque', 'Frutas');
INSERT INTO ingrediente VALUES ('Frutos secos', 'Frutas');
INSERT INTO ingrediente VALUES ('Membrillo', 'Frutas');
INSERT INTO ingrediente VALUES ('Peras', 'Frutas');
INSERT INTO ingrediente VALUES ('Manzanas', 'Frutas');
INSERT INTO ingrediente VALUES ('Uvas', 'Frutas');
INSERT INTO ingrediente VALUES ('Fruta seca', 'Frutas');
INSERT INTO ingrediente VALUES ('Frambuesa', 'Frutas');
INSERT INTO ingrediente VALUES ('Fresa', 'Frutas');
INSERT INTO ingrediente VALUES ('Granada', 'Frutas');
INSERT INTO ingrediente VALUES ('Higos', 'Frutas');
INSERT INTO ingrediente VALUES ('Kiwi', 'Frutas');
INSERT INTO ingrediente VALUES ('Limón', 'Frutas');
INSERT INTO ingrediente VALUES ('Mandarina', 'Frutas');
INSERT INTO ingrediente VALUES ('Melón', 'Frutas');
INSERT INTO ingrediente VALUES ('Naranja', 'Frutas');
INSERT INTO ingrediente VALUES ('Piña', 'Frutas');
INSERT INTO ingrediente VALUES ('Plátano', 'Frutas');
INSERT INTO ingrediente VALUES ('Pomelo', 'Frutas');
INSERT INTO ingrediente VALUES ('Sandía', 'Frutas');
INSERT INTO ingrediente VALUES ('Atún', 'Pescado');
INSERT INTO ingrediente VALUES ('Anchoa', 'Pescado');
INSERT INTO ingrediente VALUES ('Bacalao', 'Pescado');
INSERT INTO ingrediente VALUES ('Bonito', 'Pescado');
INSERT INTO ingrediente VALUES ('Boquerón', 'Pescado');
INSERT INTO ingrediente VALUES ('Caballa', 'Pescado');
INSERT INTO ingrediente VALUES ('Chicharro', 'Pescado');
INSERT INTO ingrediente VALUES ('Corvina', 'Pescado');
INSERT INTO ingrediente VALUES ('Dorada', 'Pescado');
INSERT INTO ingrediente VALUES ('Lenguado', 'Pescado');
INSERT INTO ingrediente VALUES ('Lubina', 'Pescado');
INSERT INTO ingrediente VALUES ('Merluza', 'Pescado');
INSERT INTO ingrediente VALUES ('Mero', 'Pescado');
INSERT INTO ingrediente VALUES ('Palometa', 'Pescado');
INSERT INTO ingrediente VALUES ('Pejerrey', 'Pescado');
INSERT INTO ingrediente VALUES ('Rape', 'Pescado');
INSERT INTO ingrediente VALUES ('Rodaballo', 'Pescado');
INSERT INTO ingrediente VALUES ('Salmón', 'Pescado');
INSERT INTO ingrediente VALUES ('Sardina', 'Pescado');
INSERT INTO ingrediente VALUES ('Trucha', 'Pescado');
INSERT INTO ingrediente VALUES ('Camarón', 'Marisco');
INSERT INTO ingrediente VALUES ('Cigala', 'Marisco');
INSERT INTO ingrediente VALUES ('Gamba', 'Marisco');
INSERT INTO ingrediente VALUES ('Langostino', 'Marisco');
INSERT INTO ingrediente VALUES ('Percebe', 'Marisco');
INSERT INTO ingrediente VALUES ('Almeja', 'Marisco');
INSERT INTO ingrediente VALUES ('Calamar', 'Marisco');
INSERT INTO ingrediente VALUES ('Mejillón', 'Marisco');
INSERT INTO ingrediente VALUES ('Ostra', 'Marisco');
INSERT INTO ingrediente VALUES ('Pulpo', 'Marisco');
INSERT INTO ingrediente VALUES ('Sepia', 'Marisco');
INSERT INTO ingrediente VALUES ('Vieira', 'Marisco');
INSERT INTO ingrediente VALUES ('Cordero', 'Carnes');
INSERT INTO ingrediente VALUES ('Ovejas', 'Carnes');
INSERT INTO ingrediente VALUES ('Ternera', 'Carnes');
INSERT INTO ingrediente VALUES ('Buey', 'Carnes');
INSERT INTO ingrediente VALUES ('Caballo', 'Carnes');
INSERT INTO ingrediente VALUES ('Cabra', 'Carnes');
INSERT INTO ingrediente VALUES ('Cerdo', 'Carnes');
INSERT INTO ingrediente VALUES ('Vaca', 'Carnes');
INSERT INTO ingrediente VALUES ('Avestruz', 'Carnes');
INSERT INTO ingrediente VALUES ('Paloma', 'Carnes');
INSERT INTO ingrediente VALUES ('Perdiz', 'Carnes');
INSERT INTO ingrediente VALUES ('Patos', 'Carnes');
INSERT INTO ingrediente VALUES ('Pavos', 'Carnes');
INSERT INTO ingrediente VALUES ('Ocas', 'Carnes');
INSERT INTO ingrediente VALUES ('Gallinas', 'Carnes');
INSERT INTO ingrediente VALUES ('Pollo', 'Carnes');
INSERT INTO ingrediente VALUES ('capones', 'Carnes');
INSERT INTO ingrediente VALUES ('Bison', 'Carnes');
INSERT INTO ingrediente VALUES ('Conejo', 'Carnes');
INSERT INTO ingrediente VALUES ('Liebre', 'Carnes');
INSERT INTO ingrediente VALUES ('Oso', 'Carnes');
INSERT INTO ingrediente VALUES ('Ciervo', 'Carnes');
INSERT INTO ingrediente VALUES ('Jabalí', 'Carnes');
INSERT INTO ingrediente VALUES ('Patos', 'Carnes');
INSERT INTO ingrediente VALUES ('Faisanes', 'Carnes');
INSERT INTO ingrediente VALUES ('Ocas salvajes', 'Carnes');
INSERT INTO ingrediente VALUES ('Spaghetti', 'Pasta');
INSERT INTO ingrediente VALUES ('Tallarines', 'Pasta');
INSERT INTO ingrediente VALUES ('Macarrones', 'Pasta');
INSERT INTO ingrediente VALUES ('Gnocchi', 'Pasta');
INSERT INTO ingrediente VALUES ('Ravioli', 'Pasta');
INSERT INTO ingrediente VALUES ('Tortellini', 'Pasta');
INSERT INTO ingrediente VALUES ('Arborio', 'Arroz');
INSERT INTO ingrediente VALUES ('Largo', 'Arroz');
INSERT INTO ingrediente VALUES ('Bomba', 'Arroz');
INSERT INTO ingrediente VALUES ('Basmati', 'Arroz');
INSERT INTO ingrediente VALUES ('Macis', 'Especias');
INSERT INTO ingrediente VALUES ('Ajowan', 'Especias');
INSERT INTO ingrediente VALUES ('Alcaravea', 'Especias');
INSERT INTO ingrediente VALUES ('Alhova', 'Especias');
INSERT INTO ingrediente VALUES ('Almendra', 'Especias');
INSERT INTO ingrediente VALUES ('Amapola', 'Especias');
INSERT INTO ingrediente VALUES ('Anís verde', 'Especias');
INSERT INTO ingrediente VALUES ('Anís estrellado', 'Especias');
INSERT INTO ingrediente VALUES ('Agracejo', 'Especias');
INSERT INTO ingrediente VALUES ('Cardamomo', 'Especias');
INSERT INTO ingrediente VALUES ('Cardamomo negro', 'Especias');
INSERT INTO ingrediente VALUES ('Guindilla', 'Especias');
INSERT INTO ingrediente VALUES ('Comino', 'Especias');
INSERT INTO ingrediente VALUES ('Comino negro', 'Especias');
INSERT INTO ingrediente VALUES ('Cubeba', 'Especias');
INSERT INTO ingrediente VALUES ('Eneldo', 'Especias');
INSERT INTO ingrediente VALUES ('Granos de paraíso', 'Especias');
INSERT INTO ingrediente VALUES ('Haba tonka', 'Especias');
INSERT INTO ingrediente VALUES ('Enebro', 'Especias');
INSERT INTO ingrediente VALUES ('Mostaza', 'Especias');
INSERT INTO ingrediente VALUES ('Nigella', 'Especias');
INSERT INTO ingrediente VALUES ('Nuez moscada', 'Especias');
INSERT INTO ingrediente VALUES ('Pimentón', 'Especias');
INSERT INTO ingrediente VALUES ('Pimienta', 'Especias');
INSERT INTO ingrediente VALUES ('Pimienta de Sichuan', 'Especias');
INSERT INTO ingrediente VALUES ('Pimenta dioica', 'Especias');
INSERT INTO ingrediente VALUES ('Pimienta larga', 'Especias');
INSERT INTO ingrediente VALUES ('Tamarindo', 'Especias');
INSERT INTO ingrediente VALUES ('Apio', 'Especias');
INSERT INTO ingrediente VALUES ('Semillas de granada', 'Especias');
INSERT INTO ingrediente VALUES ('Sésamo', 'Especias');
INSERT INTO ingrediente VALUES ('Vainilla', 'Especias');
INSERT INTO ingrediente VALUES ('Zumaque', 'Especias');
INSERT INTO ingrediente VALUES ('Canela', 'Especias');
INSERT INTO ingrediente VALUES ('Cassia', 'Especias');
INSERT INTO ingrediente VALUES ('Azafrán', 'Especias');
INSERT INTO ingrediente VALUES ('Clavo de olor', 'Especias');
INSERT INTO ingrediente VALUES ('Lavanda', 'Especias');
INSERT INTO ingrediente VALUES ('Rosa', 'Especias');
INSERT INTO ingrediente VALUES ('Raíces', 'Especias');
INSERT INTO ingrediente VALUES ('Regaliz', 'Especias');
INSERT INTO ingrediente VALUES ('Rúcula', 'Especias');
INSERT INTO ingrediente VALUES ('Wasabi', 'Especias');
INSERT INTO ingrediente VALUES ('Resinas', 'Especias');
INSERT INTO ingrediente VALUES ('Asafétida', 'Especias');
INSERT INTO ingrediente VALUES ('Alpinia officinarum', 'Especias');
INSERT INTO ingrediente VALUES ('Cúrcuma', 'Especias');
INSERT INTO ingrediente VALUES ('Jengibre', 'Especias');
INSERT INTO ingrediente VALUES ('Galanga', 'Especias');
INSERT INTO ingrediente VALUES ('Ajedrea', 'Especias');
INSERT INTO ingrediente VALUES ('Ajedrea de jardín', 'Especias');
INSERT INTO ingrediente VALUES ('Angélica', 'Especias');
INSERT INTO ingrediente VALUES ('Albahaca', 'Especias');
INSERT INTO ingrediente VALUES ('Árbol del curry', 'Especias');
INSERT INTO ingrediente VALUES ('Cantueso', 'Especias');
INSERT INTO ingrediente VALUES ('Cilantro', 'Especias');
INSERT INTO ingrediente VALUES ('Espliego', 'Especias');
INSERT INTO ingrediente VALUES ('Estragón', 'Especias');
INSERT INTO ingrediente VALUES ('Eneldo', 'Especias');
INSERT INTO ingrediente VALUES ('Hinojo', 'Especias');
INSERT INTO ingrediente VALUES ('Laurel', 'Especias');
INSERT INTO ingrediente VALUES ('Levístico', 'Especias');
INSERT INTO ingrediente VALUES ('Malabathrum', 'Especias');
INSERT INTO ingrediente VALUES ('Mejorana', 'Especias');
INSERT INTO ingrediente VALUES ('Menta', 'Especias');
INSERT INTO ingrediente VALUES ('Menta piperita', 'Especias');
INSERT INTO ingrediente VALUES ('Menta poleo', 'Especias');
INSERT INTO ingrediente VALUES ('Orégano', 'Especias');
INSERT INTO ingrediente VALUES ('Perejil', 'Especias');
INSERT INTO ingrediente VALUES ('Perifollo', 'Especias');
INSERT INTO ingrediente VALUES ('Ruda', 'Especias');
INSERT INTO ingrediente VALUES ('Salvia', 'Especias');
INSERT INTO ingrediente VALUES ('Romero', 'Especias');
INSERT INTO ingrediente VALUES ('Tomillo', 'Especias');
INSERT INTO ingrediente VALUES ('Curry', 'Especias');
INSERT INTO ingrediente VALUES ('Ajo en polvo', 'Especias');
INSERT INTO ingrediente VALUES ('Apio en polvo', 'Especias');
INSERT INTO ingrediente VALUES ('Cebolla seca', 'Especias');
INSERT INTO ingrediente VALUES ('Pimentón', 'Especias');
INSERT INTO ingrediente VALUES ('Tomate secado y en polvo', 'Especias');
INSERT INTO ingrediente VALUES ('Ancas de rana', 'Otros');
INSERT INTO ingrediente VALUES ('Caracoles', 'Otros');
INSERT INTO ingrediente VALUES ('Cereales', 'Otros');
INSERT INTO ingrediente VALUES ('Harinas', 'Otros');
INSERT INTO ingrediente VALUES ('Panes', 'Otros');
INSERT INTO ingrediente VALUES ('Huevos', 'Otros');
